Revert "Changed the parser such that it understands all defined functions"
This reverts commit f38cbcd651246fb5c1294705d29399f3cbfddaf5, which
broke parsing user-defined classes.

diff --git a/ginac/Makefile.am b/ginac/Makefile.am
--- a/ginac/Makefile.am
+++ b/ginac/Makefile.am
@@ -13,6 +13,7 @@ libginac_la_SOURCES = add.cpp archive.cpp basic.cpp clifford.cpp color.cpp \
   parser/parse_binop_rhs.cpp \
   parser/parser.cpp \
   parser/parse_context.cpp \
+  parser/builtin_fcns.cpp \
   parser/lexer.cpp \
   parser/lexer.h \
   parser/parser_compat.cpp \
@@ -66,7 +67,22 @@ ginacinclude_HEADERS = ginac.h add.h archive.h assertion.h basic.h class_info.h 
   parser/parser.h \
   parser/parse_context.h
 
-EXTRA_DIST = function.pl version.h.in
+EXTRA_DIST = function.pl version.h.in \
+parser/default_reader.tpl parser/builtin_fcns.def
+
+# Files produced by autogen(1) from templates
+$(srcdir)/parser/builtin_fcns.cpp: $(srcdir)/parser/builtin_fcns.def $(srcdir)/parser/default_reader.tpl
+	set -e; if [ -n "$(AUTOGEN)" ]; then \
+		cd $(srcdir)/parser; \
+		$(AUTOGEN) -T default_reader.tpl builtin_fcns.def; \
+	elif [ -f $@ ]; then \
+		echo "WARNING: AutoGen is not available, the \"$@\" file WON'T be re-generated"; \
+	else \
+		echo "*** ERROR: the \"$@\" file does not exist, and AutoGen is not installed on your system"; \
+		echo "***        Please install AutoGen (http://www.gnu.org/software/autogen)"; \
+		exit 1; \
+	fi
+		
 
 # Files which are generated by perl scripts
 $(srcdir)/function.h $(srcdir)/function.cpp: $(srcdir)/function.pl
